### ISSUE TITLE
Honeypot

### ISSUE THREAD

**Issue by fanel545** [matricali/cbrutekrag#12]
How do I activate the honeypot filter?

**Comment by fanel545** [comment]
![image](https://user-images.githubusercontent.com/36932187/73404562-75924980-42fa-11ea-8253-b5fac18557e8.png)
These from now on are a honeypot.

**Comment by matricali** [comment]
Hi @fanel545! 
The honeypot detection can be enabled using the scan phase (flag -s)

A server would be recognized as a honeypot when it self announced as an OpenSSH (ssh banner) server but they don't pass out OpenSSH fingerprinting.

I'm actually working on logic to reject servers that don't support password authentication or who implement "interactive" login, like SonicWall firewalls.

**Comment by fanel545** [comment]
![image](https://user-images.githubusercontent.com/36932187/73452459-a0b87f80-4372-11ea-8b27-2cd50381ce48.png)

I used -s and it gives me these errors

**Comment by matricali** [comment]
Ok, I'll check

**Comment by fanel545** [comment]
You checked?

**Comment by matricali** [comment]
@fanel545 I'm needing additional information in order to reproduce the case.

**Comment by matricali** [comment]
I think you aren't using the latest version...
Are you using the branch "feature/remote-command-execution" ?

**Comment by fanel545** [comment]
I have the new version and added the feature / remote-command-execution that you posted

**Comment by fanel545** [comment]
I used this command
./cbrutekrag -s -T ip -C pass -t 500 -o logs

**Comment by matricali** [comment]
Mmm OK. Can you pull the branch feature/remote-command-execution ? I’ve rebased the branch with master and resolved the conflicts

**Comment by fanel545** [comment]
I didn't understand what you said.
You tell me to download again cbrutekrag?
And to try after?

**Comment by matricali** [comment]
I've updated the branch `feature/remote-command-execution` ---> https://github.com/matricali/cbrutekrag/tree/feature/remote-command-execution

**Comment by fanel545** [comment]
![image](https://user-images.githubusercontent.com/36932187/73506737-37228a80-43df-11ea-9165-e40753081d3f.png)

Why not execute my command?
Start command -> ./cbrutekrag -s -T ip -C pass -t 500 -o logs -X "uname -a"

**Comment by fanel545** [comment]
Sorry for bothering you so much.

**Comment by matricali** [comment]
Look at your current working directory.
There should be 1 logfile per target, the content of each file should be the remote output

**Comment by fanel545** [comment]
Yes it is, but you can not show when the vps catch and command to pass it ex in the output 
-o logs file?

**Comment by matricali** [comment]
> Yes it is, but you can not show when the vps catch and command to pass it ex in the output
> -o logs file?

Current design is intended for the execution of commands that can produce more than one line
