### ISSUE TITLE
Add option to output -s (Scan) results

### ISSUE THREAD

**Issue by ariadarkkkis** [matricali/cbrutekrag#18]
Hi,
Please add an option to output filtered hosts from -s option.
Thanks

**Comment by matricali** [comment]
@ariadarkkkis Thanks for the suggestion.
I will work on this

**Comment by leakedsources** [comment]
Hello
If possible for this tool or
https://github.com/matricali/honeypot-detector/
Add this output capability
Thanks

**Comment by leakedsources** [comment]
Sorry I did not pay attention
Like you added before :))

https://github.com/matricali/cbrutekrag/tree/feature/scan-results

Thanks

**Comment by matricali** [comment]
Feature implemented in master branch. commitId: 34bacdfb2308bf34dfa2518eb8504c98da053183
It will be released in next version (probably 0.6.x)
