### ISSUE TITLE
Detect SonicWall SSH

### ISSUE THREAD

**Issue by maulvi** [matricali/cbrutekrag#20]
I still got many duplicates output from honeypot would be great if cbrutekrag could skip the same cracked IP

**Comment by matricali** [comment]
Hi @maulvi, sorry for the late response
You can simply skip the targets that have been identified as a honeypot, so you can avoid false positives, etc.
It is convenient for you?

You can discard any non-bruteforceable targets activating the "scan phase" using -s argument

**Comment by maulvi** [comment]
-s argument is not effective against sonicwall SSH firewall because it looks like legit openssh act like honeypot accept any password but has secondary login in ssh terminal, resulting many IP duplicates.
example
https://i.imgur.com/nEv6WTv.png

**Comment by matricali** [comment]
Hi @maulvi . Thanks for your feedback
Let me investigate this scenario

**Comment by Little-Potato01** [comment]
May I ask if this issue has been resolved?
