### ISSUE TITLE
static build compile error...help

### ISSUE THREAD

**Issue by Os1r** [matricali/cbrutekrag#25]
[root@localhost cbrutekrag]# ./static-build.sh
~/test/cbrutekrag/external/libssh-0.9.3/build ~/test/cbrutekrag
-- Could NOT find NaCl (missing: NACL_LIBRARIES NACL_INCLUDE_DIRS)
-- Threads_FOUND=TRUE
-- ********************************************
-- ********** libssh build options : **********
-- zlib support: ON
-- libgcrypt support: OFF
-- libmbedTLS support: OFF
-- libnacl support: OFF
-- SFTP support: ON
-- Server support : ON
-- GSSAPI support : ON
-- GEX support : ON
-- Pcap debugging support : ON
-- Build shared library: OFF
-- Unit testing: OFF
-- Client code testing: OFF
-- Blowfish cipher support: OFF
-- Server code testing: OFF
-- Public API documentation generation
-- Benchmarks: OFF
-- Symbol versioning: ON
-- Allow ABI break: OFF
-- Release is final:
-- Global client config: /etc/ssh/ssh_config
-- Global bind config: /etc/ssh/libssh_server_config
-- ********************************************
-- Configuring done
-- Generating done
-- Build files have been written to: /root/test/cbrutekrag/external/libssh-0.9.3/build
[  1%] Searching for files
[  1%] Built target dev_header_list_int
[  1%] Built target dev_header_list
[  2%] Extracting symbols from headers
[  2%] Built target libssh_dev.symbols_int
[  2%] Built target libssh_dev.symbols
[  4%] Generating the map libssh_dev.map
[WARNING] Overwriting existing file '/root/test/cbrutekrag/external/libssh-0.9.3/build/src/libssh_dev.map'
No symbols added or removed. Nothing done.
[  4%] Built target libssh_dev.map_int
[  4%] Built target libssh_dev.map
[100%] Built target ssh
~/test/cbrutekrag
rm -f obj/cbrutekrag.o obj/log.o obj/str.o obj/iprange.o obj/progressbar.o obj/bruteforce_ssh.o obj/detection.o obj/target.o obj/credentials.o obj/macrowrapper.o
mkdir -p obj
Compiled src/cbrutekrag.c successfully!
Compiled src/log.c successfully!
Compiled src/str.c successfully!
Compiled src/iprange.c successfully!
Compiled src/progressbar.c successfully!
Compiled src/bruteforce_ssh.c successfully!
Compiled src/detection.c successfully!
Compiled src/target.c successfully!
Compiled src/credentials.c successfully!
Compiled src/macrowrapper.c successfully!
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [cbrutekrag] Error 1

**Comment by Os1r** [comment]
i figuret out..

**Comment by matricali** [comment]
Could you add more details? Maybe this information will be useful to someone else having the same error.
