### ISSUE TITLE
Support for use hostname as password

### ISSUE THREAD

**Issue by scotch123** [matricali/cbrutekrag#28]
Is any chance to set a placeholder for password like for example #DOMAIN#  and try the password as the domain ?

I mean let say I have abc.com , i want to put in combos.txt as password #DOMAIN# and to try as password abc.com . any chance? thanks!

**Comment by scotch123** [comment]
Sorry for my delay, i was away from pc few weeks.. I've checked the modified code but it doesn't find the vulnerable host with the password as the hostname. on verbose mode it shows that is trying that password as the hostname but it doesn't validate any

**Comment by matricali** [comment]
@scotch123 Thanks for your feedback. A fix has been applied

**Comment by scotch123** [comment]
Yes, it works, thanks! ;x
