### ISSUE TITLE
Parsing error , Invalid port

### ISSUE THREAD

**Issue by cac4444** [matricali/cbrutekrag#35]
if this script is not the fastest script , its one of the best and fastest ssh brute tools on github  ,but in version 0.6.0 when  trying to brute ip addrsses from list  code gives error (An error occurred parsing ... on line .. , Ivalid port (22 ) format of file is ip:port , i tried previous versions and they were fine 

![photo_2024-08-13_09-22-10](https://github.com/user-attachments/assets/762e863d-4ecc-4fb0-98ee-a14f98be1c8b)

**Comment by matricali** [comment]
Look like your file has CRLF line endings instead of LF
