### ISSUE TITLE
Support for port on the targets list

### ISSUE THREAD

**Issue by najachai** [matricali/cbrutekrag#5]
Hello author!
This is a very good project. But I think he can improve it.
When infiltrating into the internal network, we often encounter many SSH protocols for non-standard ports.
When loading a target, I want to test the target in this format.
192.168.1.1#Default 22
192.168.1.2:2222
192.168.1.3:22022
This allows you to test different target ports simultaneously. If you do this, you don't need the -p parameter.
                                                                                                   Looking forward to your reply

**Comment by matricali** [comment]
Hi @najachai,

It's curious that you mention this because I've been thinking to add this feature exactly as you describe :D
I will work on this for the next release :+1: 

Thanks for your support!

**Comment by matricali** [comment]
I also would like to add support for port ranges.
Ie: -p 22,2022,2200-2299

What do you think?

**Comment by najachai** [comment]
> 我还想添加对端口范围的支持。
> 即：-p 22,2022,2200-2299
> 
> 你怎么看？

Are you referring to the scan mode?
This is good!

**Comment by najachai** [comment]
> 我还想添加对端口范围的支持。
> 即：-p 22,2022,2200-2299
> 
> 你怎么看？

In most cases, masscan is used to scan the port because he is very fast

**Comment by matricali** [comment]
Conceptually, cbrutekrag works on three different phases

1. Build targets list (Literal list OR Scan + Honeypot detection)
2. Build combinations, host+port+username+password (this is the total amount of login tries)
3. Bruteforce!

**Comment by matricali** [comment]
Regarding the use of ports in the list of objectives, you are probably working on it this week.

We are also working on other new features.
Would you like to see the other issues and discuss them?

**Comment by najachai** [comment]
> 关于目标列表中端口的使用，您可能会在本周内进行处理。
> 
> 我们还在开发其他新功能。
> 您想看到其他问题并进行讨论吗？
I will look at other issues and pay attention and discussion! Looking forward to your next version update!
👍

**Comment by najachai** [comment]
> 关于目标列表中端口的使用，您可能会在本周内进行处理。
> 
> 我们还在开发其他新功能。
> 您想看到其他问题并进行讨论吗？

I will look at other issues and pay attention and discussion! Looking forward to your next version update!👍

**Comment by matricali** [comment]
@najachai I'm working on this in a specific branch: `feature/5-custom-port-on-target-list`
I've pushed the initial base. At this moment it is possible to specify a single target port per line, but CIDR blocks can be used.

* `192.168.100.5`: Adds a single target, using 192.168.100.5 as host, and port specified using -p argument, default instead (22)
* `192.168.100.5`: Adds a single target, using 192.168.100.5 as host and 2222 as the port
* `192.168.100.0/24`: Adds many targets, from 192.168.100.0 to 192.168.100.255, and port specified using -p argument, default instead (22)
* `192.168.100.0/24:2222`: Adds many targets, from 192.168.100.0 to 192.168.100.255, and 2222 as the port

This acts on the "target list building" phase, so we can use later on the   "scan phase" and "brute-force phase"

**Comment by najachai** [comment]
> @najachai I'm working on this in a specific branch: `feature/5-custom-port-on-target-list`
> I've pushed the initial base. At this moment it is possible to specify a single target port per line, but CIDR blocks can be used.
> 
> * `192.168.100.5`: Adds a single target, using 192.168.100.5 as host, and port specified using -p argument, default instead (22)
> * `192.168.100.5`: Adds a single target, using 192.168.100.5 as host and 2222 as the port
> * `192.168.100.0/24`: Adds many targets, from 192.168.100.0 to 192.168.100.255, and port specified using -p argument, default instead (22)
> * `192.168.100.0/24:2222`: Adds many targets, from 192.168.100.0 to 192.168.100.255, and 2222 as the port
> 
> This acts on the "target list building" phase, so we can use later on the "scan phase" and "brute-force phase"
> 
> You can view these changes on [511c462](https://github.com/matricali/cbrutekrag/commit/511c462b69cad6911b3eddfa38725257aaae9d68)

ok！I will take the time to test! thank you

**Comment by matricali** [comment]
@najachai any feedback on this?

**Comment by najachai** [comment]
No problem at the moment

**Comment by matricali** [comment]
I close this issue since custom port support has been merged into the "master" branch.

Port ranges still pending (We will work on this on #6)
